<?php

const IBLOCK_ID_DOCTORS = 16;
const IBLOCK_ID_PROCEDURES = 17;
const IBLOCK_ID_OTUS_TASKS = 21;
const IBLOCK_ID_OTUS_EMPLOYEE = 20;
const IBLOCK_ID_OTUS_PROJECT = 19;
const IBLOCK_ID_OTUS_BOOKING = 22;
const IBLOCK_ID_ACCOUNTING_ORDERS = 23;